apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: public-repo
  description: Public demo repo for Backstage
  labels:
    team: devops
  annotations:
    backstage.io/source-location: url:https://raw.githubusercontent.com/spelluri/GitOps-Jenkins-Project/main/catalog-info.yaml
spec:
  type: service
  lifecycle: experimental
  owner: user:default/spelluri
